import type { ExtractedCodeContext } from "./types";
import type { RankedCompletion } from "./types";

export function genericPatternForEmptyFile(languageId: string): RankedCompletion | undefined {
  const commentByLang: Record<string, string> = {
    typescript: "// ",
    javascript: "// ",
    python: "# ",
    java: "// ",
    csharp: "// ",
    go: "// ",
    rust: "// ",
    sql: "-- "
  };
  const prefix = commentByLang[languageId] ?? "// ";
  return { text: `${prefix}Generated by Coop AI\n`, score: 0.2, source: "pattern" };
}

export function adjustForSyntaxRisk(
  completions: RankedCompletion[],
  riskySyntax: boolean
): RankedCompletion[] {
  if (!riskySyntax) {
    return completions;
  }
  return completions.map((item) => ({ ...item, score: item.score * 0.85 }));
}

export function detectIndentation(lines: string[]): string {
  for (let i = lines.length - 1; i >= 0; i -= 1) {
    const line = lines[i];
    if (!line.trim()) {
      continue;
    }
    const match = /^(\s+)/.exec(line);
    if (match) {
      return match[1];
    }
    break;
  }
  return "";
}

export function normalizeMixedIndent(text: string, indent: string): string {
  if (!indent) {
    return text;
  }
  const usesTabs = indent.includes("\t");
  const lines = text.split("\n");
  return lines
    .map((line, index) => {
      if (index === 0 || !line) {
        return line;
      }
      const stripped = line.replace(/^[\t ]+/, "");
      const level = (line.match(/^[\t ]+/)?.[0] ?? "").length;
      const unit = usesTabs ? "\t" : "  ";
      const repeat = Math.max(1, Math.ceil(level / 2));
      return indent + unit.repeat(repeat - 1) + stripped;
    })
    .join("\n");
}

export function truncateOversizedImports(importsBlock: string, maxChars = 500): string {
  if (importsBlock.length <= maxChars) {
    return importsBlock;
  }
  const lines = importsBlock.split("\n");
  const kept: string[] = [];
  let size = 0;
  for (const line of lines) {
    if (size + line.length + 1 > maxChars) {
      break;
    }
    kept.push(line);
    size += line.length + 1;
  }
  return kept.join("\n");
}

export function fallbackWhenNoContext(
  languageId: string,
  indent: string
): RankedCompletion | undefined {
  const snippets: Record<string, string> = {
    typescript: "function example() {\n  \n}",
    javascript: "function example() {\n  \n}",
    python: "def example():\n    pass",
    java: "public void example() {\n  \n}",
    sql: "SELECT *\nFROM "
  };
  const body = snippets[languageId];
  if (!body) {
    return undefined;
  }
  return { text: indent + body.split("\n").join(`\n${indent}`), score: 0.15, source: "pattern" };
}

export function applyEdgeCaseFallbacks(
  context: ExtractedCodeContext,
  completions: RankedCompletion[]
): RankedCompletion[] {
  if (completions.length > 0) {
    return adjustForSyntaxRisk(completions, context.riskySyntax);
  }
  const isEmptyFile =
    !context.previousLines.trim() &&
    !context.currentLinePrefix.trim() &&
    !context.importsBlock.trim();
  if (isEmptyFile) {
    const generic = genericPatternForEmptyFile(context.languageId);
    return generic ? [generic] : [];
  }
  if (!context.previousLines.trim()) {
    const fallback = fallbackWhenNoContext(context.languageId, context.indent);
    return fallback ? adjustForSyntaxRisk([fallback], context.riskySyntax) : [];
  }
  return [];
}
